### ISSUE TITLE
Please also add some guidance how to sync via IoTHub

### ISSUE THREAD

**Issue by alaendle** [veyalla/ehm#1]
Many thanks for providing the possibility to sync IoT edge metrics in some standard way (this was exactly the feature we have missed so far) to the cloud. It works as expected with the direct sync to log analytics - however I also want to try out the support of offline/disconnected scenarios and so I would also like to test the way to sync via IoTHub/D2C messages.

Since it was a pleasure to follow your guide to implement the log analytics connection, I would like to ask to also add some similar guidance for the D2C-way.

Thanks in advance!

**Comment by veyalla** [comment]
@alaendle Glad you found it useful! I've updated the readme to show a way to ingest metrics send via IoT Hub.

**Comment by alaendle** [comment]
@veyalla Many thanks; also works like a charm - maybe you would like to mention that a route need to be defined to forward messages from MetricsCollector module to upstream (one of the minor problems I stumbled across while implementing your approach).
