### ISSUE TITLE
MetricsCollector module should react to device twin changes

### ISSUE THREAD

**Issue by alaendle** [veyalla/ehm#3]
## Expected Behavior
If the device twin is changed, means the scraped prometheus endpoints chance, e.g. because a new module is added, the MetricsCollector module should recognize that.

## Current Behavior
At the moment the MetricsCollector just evaluates it's device twin on start-up. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Deploy MetricsCollector module
2. Add another edge module exposing a prometheus endpoint
3. Add the prometheus endpoint to the endpoints-list of the MetricsCollector device twin
4. Note that the new endpoint is not scraped

## Additional Information
Please note that the current behaviour basically mean you have to stop/start the MetricsCollector every time the list of prometheus endpoints changes. This is very inconvenient if you have no direct access to the edge and are forced to do two deployments via the Azure portal just to stop and start the MetricsCollector module in order to refresh the prometheus endpoint list.

**Comment by alaendle** [comment]
Replica of https://github.com/Azure/iotedge/issues/2551

**Comment by veyalla** [comment]
In general, please don't expect too much support for the *sample* metrics collector while the end-to-end UX for the feature is being developed. 

That being said, will be moving the metrics collector *sample* to read its config from env variable instead of twin so it can updated at the same time you're adding a new module to be scraped for example...

**Comment by alaendle** [comment]
@veyalla Sorry, didn't want to cause any stress. My impression was that since the code was moved to the official repository that this _sample_ got an upgrade to be a more mature module that might become the base for future metrics handling. No offense meant. And many thanks for the active development of the feature regarding metrics/monitoring - I really believe that these were missing so far and that the loosely coupled, standardized way using prometheus is a good idea!

**Comment by veyalla** [comment]
No stress, no offense taken :) 

The reason the metrics collector was moved to the main repo is because it's being leveraged it in IoT Edge's test infra. Don't have plans to offer it as a supported first-party module at this time.

**Comment by veyalla** [comment]
Sample has been migrated to: https://labs.iotedge.dev/codelabs/monitor-iotedge

This should be fixed there.
