### ISSUE TITLE
Fails on Raspberry Pi

### ISSUE THREAD

**Issue by henioStraszny** [veyalla/ehm#6]
I've setup IoT Edge and I cannot make metricscollector to work there. Container fails with following error:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

My suspicion is that docker image should be build against different architecture. Is that correct?

Board: Raspberry Pi 3 Model B Rev 1.2
OS: Raspbian GNU/Linux 9 (stretch)
Docker version 3.0.13+azure, build dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
iotedge 1.0.9.3
container: veyalla/metricscollector:0.0.4-amd64
uname-m: armv7l

**Comment by veyalla** [comment]
Sample has been migrated to: https://labs.iotedge.dev/codelabs/monitor-iotedge 

This should be fixed there.
